# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
###
version: 2.1

orbs:
  aws: circleci/aws-cli@3.1.1
  ecr: circleci/aws-ecr@8.1.2
  ecs: circleci/aws-ecs@2.2.1
executers:
  banksimulation:
    parameters:
      tag:
        type: string
    docker:
      - image: 289073749577.dkr.ecr.us-east-1.amazonaws.com/banksimulation:latest

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.2
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - ecr/build-and-push-image:
          repo: banksimulation
          tag: latest
  aws-cli-example:
    executor: aws/default
    steps:
      - aws/setup
      - run:
          name: Use AWS CLI
          command: aws --version
  test:
    executor:
      name: banksimulation
      tag: latest
    steps:
      - run: npm test
workflows:
  build_and_test:
    jobs:
      - build:
          context:
            - aws

      - aws-cli-example:
          context:
              - aws
          requires:
            - build
      - test:
          context:
            - aws
          requires:
            - build
